# Generated by Django 4.2 on 2023-05-01 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Mavzu matni'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tasks',
            field=ckeditor.fields.RichTextField(verbose_name='Vazifalar'),
        ),
    ]
