# Generated by Django 4.2 on 2023-05-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_topic_body_alter_topic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer_a', models.CharField(max_length=400, verbose_name='A javob:')),
                ('answer_b', models.CharField(max_length=400, verbose_name='b javob:')),
                ('answer_c', models.CharField(max_length=400, verbose_name='C javob:')),
                ('answer_d', models.CharField(max_length=400, verbose_name='D javob:')),
                ('answer', models.CharField(choices=[('answer_a', 'A javob'), ('answer_b', 'B javob'), ('answer_c', 'C javob'), ('answer_d', 'D javob')], default='answer_a', max_length=10, verbose_name='Javob:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_topic', to='main.topic')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
            },
        ),
    ]
